/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as DocsRouteImport } from './app/docs'
import { Route as E2eRouteImport } from './app/e2e'
import { Route as ExamplesRouteImport } from './app/examples'
import { Route as MultiRouteImport } from './app/multi'
import { Route as SubframeRouteImport } from './app/subframe'
import { Route as DocsIndexRouteImport } from './app/docs/index'
import { Route as DocsSlugRouteImport } from './app/docs/$slug'
import { Route as DocsDemosRouteImport } from './app/docs/demos'
import { Route as E2eOnlyofficeFactoryRouteImport } from './app/e2e/onlyoffice-factory'
import { Route as E2eRuntimeRegressionsRouteImport } from './app/e2e/runtime-regressions'
import { Route as DocsDemosIndexRouteImport } from './app/docs/demos/index'
import { Route as DocsDemosMultiRouteImport } from './app/docs/demos/multi'
import { Route as DocsDemosSingleRouteImport } from './app/docs/demos/single'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRoute = E2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const SubframeRoute = SubframeRouteImport.update({
  id: '/subframe',
  path: '/subframe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDemosRoute = DocsDemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => DocsRoute,
} as any)
const E2eOnlyofficeFactoryRoute = E2eOnlyofficeFactoryRouteImport.update({
  id: '/onlyoffice-factory',
  path: '/onlyoffice-factory',
  getParentRoute: () => E2eRoute,
} as any)
const E2eRuntimeRegressionsRoute = E2eRuntimeRegressionsRouteImport.update({
  id: '/runtime-regressions',
  path: '/runtime-regressions',
  getParentRoute: () => E2eRoute,
} as any)
const DocsDemosIndexRoute = DocsDemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsDemosRoute,
} as any)
const DocsDemosMultiRoute = DocsDemosMultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => DocsDemosRoute,
} as any)
const DocsDemosSingleRoute = DocsDemosSingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => DocsDemosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/e2e': typeof E2eRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/multi': typeof MultiRoute
  '/subframe': typeof SubframeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/demos': typeof DocsDemosRouteWithChildren
  '/e2e/onlyoffice-factory': typeof E2eOnlyofficeFactoryRoute
  '/e2e/runtime-regressions': typeof E2eRuntimeRegressionsRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/demos/multi': typeof DocsDemosMultiRoute
  '/docs/demos/single': typeof DocsDemosSingleRoute
  '/docs/demos/': typeof DocsDemosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e2e': typeof E2eRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/multi': typeof MultiRoute
  '/subframe': typeof SubframeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/e2e/onlyoffice-factory': typeof E2eOnlyofficeFactoryRoute
  '/e2e/runtime-regressions': typeof E2eRuntimeRegressionsRoute
  '/docs': typeof DocsIndexRoute
  '/docs/demos/multi': typeof DocsDemosMultiRoute
  '/docs/demos/single': typeof DocsDemosSingleRoute
  '/docs/demos': typeof DocsDemosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/e2e': typeof E2eRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/multi': typeof MultiRoute
  '/subframe': typeof SubframeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/demos': typeof DocsDemosRouteWithChildren
  '/e2e/onlyoffice-factory': typeof E2eOnlyofficeFactoryRoute
  '/e2e/runtime-regressions': typeof E2eRuntimeRegressionsRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/demos/multi': typeof DocsDemosMultiRoute
  '/docs/demos/single': typeof DocsDemosSingleRoute
  '/docs/demos/': typeof DocsDemosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/e2e'
    | '/examples'
    | '/multi'
    | '/subframe'
    | '/docs/$slug'
    | '/docs/demos'
    | '/e2e/onlyoffice-factory'
    | '/e2e/runtime-regressions'
    | '/docs/'
    | '/docs/demos/multi'
    | '/docs/demos/single'
    | '/docs/demos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e2e'
    | '/examples'
    | '/multi'
    | '/subframe'
    | '/docs/$slug'
    | '/e2e/onlyoffice-factory'
    | '/e2e/runtime-regressions'
    | '/docs'
    | '/docs/demos/multi'
    | '/docs/demos/single'
    | '/docs/demos'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/e2e'
    | '/examples'
    | '/multi'
    | '/subframe'
    | '/docs/$slug'
    | '/docs/demos'
    | '/e2e/onlyoffice-factory'
    | '/e2e/runtime-regressions'
    | '/docs/'
    | '/docs/demos/multi'
    | '/docs/demos/single'
    | '/docs/demos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  E2eRoute: typeof E2eRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  MultiRoute: typeof MultiRoute
  SubframeRoute: typeof SubframeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e': {
      id: '/e2e'
      path: '/e2e'
      fullPath: '/e2e'
      preLoaderRoute: typeof E2eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subframe': {
      id: '/subframe'
      path: '/subframe'
      fullPath: '/subframe'
      preLoaderRoute: typeof SubframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/demos': {
      id: '/docs/demos'
      path: '/demos'
      fullPath: '/docs/demos'
      preLoaderRoute: typeof DocsDemosRouteImport
      parentRoute: typeof DocsRoute
    }
    '/e2e/onlyoffice-factory': {
      id: '/e2e/onlyoffice-factory'
      path: '/onlyoffice-factory'
      fullPath: '/e2e/onlyoffice-factory'
      preLoaderRoute: typeof E2eOnlyofficeFactoryRouteImport
      parentRoute: typeof E2eRoute
    }
    '/e2e/runtime-regressions': {
      id: '/e2e/runtime-regressions'
      path: '/runtime-regressions'
      fullPath: '/e2e/runtime-regressions'
      preLoaderRoute: typeof E2eRuntimeRegressionsRouteImport
      parentRoute: typeof E2eRoute
    }
    '/docs/demos/': {
      id: '/docs/demos/'
      path: '/'
      fullPath: '/docs/demos/'
      preLoaderRoute: typeof DocsDemosIndexRouteImport
      parentRoute: typeof DocsDemosRoute
    }
    '/docs/demos/multi': {
      id: '/docs/demos/multi'
      path: '/multi'
      fullPath: '/docs/demos/multi'
      preLoaderRoute: typeof DocsDemosMultiRouteImport
      parentRoute: typeof DocsDemosRoute
    }
    '/docs/demos/single': {
      id: '/docs/demos/single'
      path: '/single'
      fullPath: '/docs/demos/single'
      preLoaderRoute: typeof DocsDemosSingleRouteImport
      parentRoute: typeof DocsDemosRoute
    }
  }
}

interface DocsDemosRouteChildren {
  DocsDemosMultiRoute: typeof DocsDemosMultiRoute
  DocsDemosSingleRoute: typeof DocsDemosSingleRoute
  DocsDemosIndexRoute: typeof DocsDemosIndexRoute
}

const DocsDemosRouteChildren: DocsDemosRouteChildren = {
  DocsDemosMultiRoute: DocsDemosMultiRoute,
  DocsDemosSingleRoute: DocsDemosSingleRoute,
  DocsDemosIndexRoute: DocsDemosIndexRoute,
}

const DocsDemosRouteWithChildren = DocsDemosRoute._addFileChildren(
  DocsDemosRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsDemosRoute: typeof DocsDemosRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsDemosRoute: DocsDemosRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface E2eRouteChildren {
  E2eOnlyofficeFactoryRoute: typeof E2eOnlyofficeFactoryRoute
  E2eRuntimeRegressionsRoute: typeof E2eRuntimeRegressionsRoute
}

const E2eRouteChildren: E2eRouteChildren = {
  E2eOnlyofficeFactoryRoute: E2eOnlyofficeFactoryRoute,
  E2eRuntimeRegressionsRoute: E2eRuntimeRegressionsRoute,
}

const E2eRouteWithChildren = E2eRoute._addFileChildren(E2eRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  E2eRoute: E2eRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  MultiRoute: MultiRoute,
  SubframeRoute: SubframeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
